package ro.societateahermes.backendservice.entities;

public enum ERole {
    ROLE_USER,
    ROLE_ADMIN,
    ROLE_PROJECT_MANAGER_CARIEREIT,
    ROLE_PROJECT_MANAGER_HACKATHON,
    ROLE_PROJECT_MANAGER_DESTRESIUNE,
    ROLE_PROJECT_MANAGER_GUIDEDAYS
}
